### ISSUE TITLE
Instructions incorrect

### ISSUE THREAD

**Issue by poiromaniax** [sakoula/HP-EliteDesk-800-G2-6700#1]
Hi,

During the clover config, this is incorrect. Following current guide will send you on a boot loop

copy `ELITEDESK800_EFI/CLOVER/config.plist` from the downloaded file to USB's EFI to `EFI/CLOVER/ACPI/config.plist`

should be 

copy `ELITEDESK800_EFI/CLOVER/config.plis`t from the downloaded file to USB's EFI to **EFI/CLOVER/config.plist**

Also, there is no such folder as `/Library/Extentions` it is a spelling mistake and should be `/Library/Extensions`

**Comment by sakoula** [comment]
thanks for finding this!
