### ISSUE TITLE
Update to newest catalina.

### ISSUE THREAD

**Issue by Acetyld** [sakoula/HP-EliteDesk-800-G2-6700#10]
Hey! Perhaps u got a update to newest catalina?

**Comment by sakoula** [comment]
no I am still on 10.15.3 . I did not have the time to update. However the procedure I will follow is to update clover to [Release v5.0 r5117](https://github.com/CloverHackyColor/CloverBootloader/releases) and update all the kexts to the latest version Lilu etc. 

Make sure to update the [OcQuirks](https://github.com/ReddestDream/OcQuirks) as well.

You do not need to change the config.plist

Then upgrade via the software update. 

I will do the same when I can.

Let me know if you have any questions

**Comment by Acetyld** [comment]
Yo men did you had time to ugprade to 10.15.7. I need to update right now. But if you already did clover/kext, bcs i am so afraid tbh XD let me know, i am 100% up for payment as well ^_^

**Comment by sakoula** [comment]
hey, I working on an opencore update compatible with catalina and big sur. Do not have much time now. Possibly in a month.

**Comment by sakoula** [comment]
Check my latest update. I migrated to 10.15.7 using Opencore. And I will upgrade to BigSur once available.
