### ISSUE TITLE
No internet on Hp Prodesk 600 g2 

### ISSUE THREAD

**Issue by hnr88** [sakoula/HP-EliteDesk-800-G2-6700#13]
Everything works except Ethernet. I tried to post-install IntelMausi and other all internet kexts but nothing.
Tried with Catalina and Big Sur. 
Processor: I3 6100, 16gb ddr4, Rx570  
Any ideas? 
Thanks

**Comment by sakoula** [comment]
Have you tried [IntelMausi 1.0.5](https://github.com/acidanthera/IntelMausi/releases/tag/1.0.5) ?

Is it recognized by the OS or not at all? Is the port working when you boot on another OS?

Are you using the EFI from this repository (your machine is slightly different that my EliteDesk 800)

**Comment by hnr88** [comment]
Thanks for the fast response. 
I had a dual boot configruation with Windows and Linux is worked so the card is ok.
Yes, maybe little differences but not big differences because everything else is worked, and your EFI was the first with I successfully installed the OS. Now I'm installing with IntelMausi 1.0.5 
I will keep you updated

**Comment by hnr88** [comment]
Same issue. 
At the start if I'm choosing a Local network( Ethernet) and selected DHCP Manually or whatever it's crashing and restarting. 
If I'm selecting "My computer does not connect to the internet" - it won't crash but the internet not working. 
Previously I installed Hackintosh (High Sierra) and the internet worked. So I don't know what's next.

**Comment by hnr88** [comment]
Fixed with a new Realtek Network Card.
