### ISSUE TITLE
Please update the guide for Monterey

### ISSUE THREAD

**Issue by prakharmavi** [sakoula/HP-EliteDesk-800-G2-6700#16]
please update the guide for Monterey.
and if not possible right now please tell me how to do so ,
I will do it myself

**Comment by sakoula** [comment]
unfortunately is on my to-do for some time now. Unfortunately I do not have the time. What you should do is do the exact same steps but update OpenCore and all the modules to the latest version.

**Comment by prakharmavi** [comment]
> unfortunately is on my to-do for some time now. Unfortunately I do not have the time. What you should do is do the exact same steps but update OpenCore and all the modules to the latest version.

can i use your usb map kext and ssdts in monterey?

**Comment by prakharmavi** [comment]
@sakoula i tried it it gets stuck here!


![PXL_20220527_155141517.MP.jpg](https://user-images.githubusercontent.com/91057620/170681612-80cf2829-ec98-4a20-b9f6-3d37320b2fff.jpg)

**Comment by sakoula** [comment]
are you using opencore 0.8 ? are you using all the opencore components in the latest version? also have you updated all the kexts to the latest version? If this is the case and it does not work then I have to see it. Maybe I will have some time in the next couple of weeks

**Comment by prakharmavi** [comment]
Brother have you done something?

I ended up with a bricked daily driver

**Comment by prakharmavi** [comment]
> are you using opencore 0.8 ? are you using all the opencore components in the latest version? also have you updated all the kexts to the latest version? If this is the case and it does not work then I have to see it. Maybe I will have some time in the next couple of weeks

Brother have you done something?

I ended up with a bricked daily driver
