### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by poiromaniax** [sakoula/HP-EliteDesk-800-G2-6700#2]
Hey,

Firstly thanks for this guide - Im currently following it. But I have some questions

1) What is the purpose of manually making the installer and copying all your kexts etc etc to the install disk? Why not just use Unibeast - its only the install disk after all. Surely once you have the system running you can install RehabMan's clover and do the rest?

2) I actually cannot boot into the installer using your boot disk method. It gets stuck endlessly on `kextd stall 'AppleACPICPU'`

**Comment by sakoula** [comment]
Hi Thanks for the comments.

1. Definitely you can go using the unibeast. I wanted to make sure that I was in complete control and understood exactly what I was doing. I have not tried Unibeast though.

2. The guide worked for 10.14.3 . For later Mojave versions there is a problem with the clover version that I am using in the guide (along with the clover drivers). I am actually looking these days into upgrading mine to 10.14.5 and upgrade all the hackintosh components (config.plist, clover version, clover drivers, kexts, whatever green config). Most likely I'll get it done by next week. I will post it here.

**Comment by poiromaniax** [comment]
Oh so I shouldnt follow your guide past 10.14.3?

**Comment by sakoula** [comment]
the procedure is the same however I need to upgrade versions on clover, clover drivers, kexts. I have already done it on my personal repository. I need to do some more tests in order to release it. I will get it done  by next week.

**Comment by sakoula** [comment]
Hi @poiromaniax 

I have just released a new version of the guide and attached files v0.3 which is 10.14.5 compatible. I have tested that I can boot an installation USB drive with that. I have successfully upgraded my machine to 10.14.5 following the steps of the guide. Please let me know if you have any problems with it.
