### ISSUE TITLE
Dual Monitor questions

### ISSUE THREAD

**Issue by poiromaniax** [sakoula/HP-EliteDesk-800-G2-6700#3]
> WhateverGreen: weg @ (DBG) agdpmod using config vit9696
> WhateverGreen: igfx @ (DBG) patching framebufferId 0x19120000 connector [1] busId: 0x05, pipe: 9, type: 0x00000400, flags: 0x00000187
> WhateverGreen: igfx @ (DBG) patching framebufferId 0x19120000 connector [2] busId: 0x06, pipe: 10, type: 0x00000400, flags: 0x00000187
> WhateverGreen: igfx @ (DBG) patching framebufferId 0x19120000 connector [3] busId: 0x04, pipe: 10, type: 0x00000400, flags: 0x00000187
> WhateverGreen: igfx @ (DBG) patching framebufferId 0x19120000 connector [-1] busId: 0x00, pipe: 0, type: 0x00000001, flags: 0x00000020
> 
> Patch
> 
> General > Devices/Properties
> General > Connectors
> General > Auto Detect Changes
> Advanced > FB Port Limit 3
> Device Id: 0x1912: Intel HD Graphics 530

Hey, how do I go about using Hackintool to apply this patch (I assume the top section of this is the patch "applied" and the bottom section is the config?

My patch output from Hackintool seems to contain nothing....

```
<key>Devices</key>
 <dict>
          <key>Properties</key>
          <dict/>
 </dict>
```

**Comment by poiromaniax** [comment]
Can I literally copy and paste all of this from your config to mine?

```
 <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>AAASGQ==</data>
				<key>AAPL,slot-name</key>
				<string>Internal</string>
				<key>device-id</key>
				<data>EhkAAA==</data>
				<key>framebuffer-con0-busid</key>
				<data>BQAAAA==</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-flags</key>
				<data>hwEAAA==</data>
				<key>framebuffer-con0-index</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-pipe</key>
				<data>CQAAAA==</data>
				<key>framebuffer-con0-type</key>
				<data>AAQAAA==</data>
				<key>framebuffer-con1-busid</key>
				<data>BgAAAA==</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-index</key>
				<data>AgAAAA==</data>
				<key>framebuffer-con1-pipe</key>
				<data>CgAAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-index</key>
				<data>AwAAAA==</data>
				<key>framebuffer-con3-busid</key>
				<data>AAAAAA==</data>
				<key>framebuffer-con3-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con3-flags</key>
				<data>IAAAAA==</data>
				<key>framebuffer-con3-index</key>
				<data>/////w==</data>
				<key>framebuffer-con3-pipe</key>
				<data>AAAAAA==</data>
				<key>framebuffer-con3-type</key>
				<data>AQAAAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>hda-gfx</key>
				<string>onboard-1</string>
			</dict>
```

**Comment by sakoula** [comment]
yes! this is what you should do!

HOWEVER Intel framebuffer support with multimonitor setup is known to be very buggy. I assume that you have the exact same model or a very similar one with the same framebuffer.

Follow [General Framebuffer Patching Guide](https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/) if you have a slightly different configuration.

Also what is happening in my case is that booting up with both monitors connected is working 80% of the time. What I usually do is connect just the one monitor boot up and while being on the login screen I plug the second monitor on (my computer is on 24/7 for various reasons).

**Comment by poiromaniax** [comment]
Well my monitors arent the same as yours - does that matter? (Im totally new to FB patching....)

My computer would also be on pretty much 24/7 but I dont mind hotplugging the monitor when needed....

**Comment by sakoula** [comment]
no it does not matter unless your monitors are very old. 

So try this configuration and do the hotplugging trick.

Remember that during initial installation to have only one monitor plugged in and prefer to do the installation from a usb2 port.

Let me know how it goes

**Comment by poiromaniax** [comment]
So I copied from your config and pasted into mine - apple logo starts on boot and then crashes to boot loop.

I then tried to add your boot args but same thing.

When I open hackintool and, I have BUSID's as follows:

-1
1
2
-1

And for me, clicking on Generate Patch spits out nothing.

I have no idea why

**Comment by sakoula** [comment]
which model is your computer?
have you followed my procedure? 
How did you install OSX?

**Comment by sakoula** [comment]
I am on https://gitter.im/sakoula

**Comment by poiromaniax** [comment]
EliteDesk 800 G2 TWR
I initially followed your procedure but couldn't boot at all. I then reinstalled by creating installer using UniBeast. I installed Clover from CloverConfigurator and used PaintArm2's EFI folder (Everything works great with it - full graphics acceleration, all USB's etc etc but no dual monitors)
