### ISSUE TITLE
recover from sleep 

### ISSUE THREAD

**Issue by paulierco** [sakoula/HP-EliteDesk-800-G2-6700#4]
Does recover from sleep works for both monitors?

The problem i have right now is that recover from sleep  kills one monitor connection. Most likely unplug/plugg back would work but to reboot all the time.

Now i disable sleep at all but i'm curious how is on your side?

**Comment by sakoula** [comment]
Yes I just tried and it does. however as I mentioned on the guide I disable hibernation.

```
sudo pmset -a hibernatemode 0
sudo rm /var/vm/sleepimage
sudo mkdir /var/vm/sleepimage
sudo pmset -a standby 0
sudo pmset -a autopoweroff 0
```
