### ISSUE TITLE
thanks a lot

### ISSUE THREAD

**Issue by WuLongMiTaoLaiYiDa** [sakoula/HP-EliteDesk-800-G2-6700#5]
thanks a lot , i used this EFI run Mojave10.14.6 on my elitedesk 800 G2 , i7-6700,16G ram,512G SATA SSD,lenovo rx 560 4G, mac os works very well.
i tried install Catalina, and successful installation , but when i used this os about 20min the computer suddenly rebooted without any sign.
Anyway, I want to thank you for letting me use hackintosh on my computer！:- )

**Comment by sakoula** [comment]
Hey, sorry for not replying earlier, I have not updated yet to Catalina. In your case I would (in the order of preference):

1. update Lilu, WhateverGreen, VirtualSMC
2. update clover to a newer version

**Comment by sakoula** [comment]
Hi, 

If it is still relevant, I have just updated the guide for Catalina 10.15.3
