### ISSUE TITLE
Question/Request: Creation of USB Mojave Installer from Windows

### ISSUE THREAD

**Issue by gssitrainee** [sakoula/HP-EliteDesk-800-G2-6700#6]
Noob question here, apology if this is really basic as this is my first time to try to install mac on a pc.

I do not own any mac machine and I cannot proceed with the creation of USB mojave installer.
Is there a way that I can create the usb mojave installer from windows?

Also, how can I download mojave installer that will be used in the usb... since I do not own a mac?

Any suggestion of iso or mojave installer that I can search? I found niresh mojave and transmac... but I got some comments in fb groups that this pc wont work with niresh methods.

Again, apology if my question/request is too basic.. I got lost for days trying to setup mac on this pc.

Thanks

**Comment by sakoula** [comment]
Hi, 

Did you figure out how to do it?

have you checked this? https://internet-install.gitbook.io/macos-internet-install/

What type of computer do you want to install macos at?
