### ISSUE TITLE
Failed to detect supported...

### ISSUE THREAD

**Issue by Acetyld** [sakoula/HP-EliteDesk-800-G2-6700#7]
Hey first off big thanks! I love the work you do, when its done ill donate 10/10.

But i am stuck on this.
![afbeelding](https://user-images.githubusercontent.com/55088242/75717894-4e9cae00-5cd2-11ea-9a46-b3ca245a53f1.png)

**Comment by Acetyld** [comment]
UPDATE: after change of usb port ( i was using 3.0 on the back) so i plugged in the 2.0 usb side and now i got this error:
![Screenshot_20200302-222414](https://user-images.githubusercontent.com/55088242/75719745-996bf500-5cd5-11ea-8b88-1875bd1139d7.jpg)

**Comment by sakoula** [comment]
Hi There,

So:

* Which hardware are you using and which BIOS do you have
* Are you trying to install catalina from scratch or trying to update?
* Attach the EFI partition that you are booting from in this thread.

**Comment by Acetyld** [comment]
https://www.reddit.com/r/hackintosh/comments/fef89u/refurbished_beast_i7_6700_rx_560_4gb_32gb_ddr4/
Thank you for the respond!

Got everything working

**Comment by sakoula** [comment]
hey

I am really glad that everything worked for you!!!
Great great reditt post!!

out of curiosity. What kind of hardware spec do you have? can you share your working efi partition? I am really interested to the changes you made

Also which are the monitors you are using?
