### ISSUE TITLE
Wireless / bluetooth Instructions

### ISSUE THREAD

**Issue by ryanmerolle** [sakoula/HP-EliteDesk-800-G2-6700#8]
I am not sure anyone has tried the BMC wifi m.2 mini pcie x1 chip with this EliteDesk, but I ordered one on ebay and will try it out to see what I can add to this repo.

**Comment by sakoula** [comment]
hey,
on my other z390 hackintosh I have successfully used what is being described here

https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/
